
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform -chdir=terraform_code init

    - name: Terraform Apply
      run: terraform -chdir=terraform_code apply -auto-approve -var-file=input.tfvars

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    needs: terraform-apply

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and deploy backend
      run: |
        gcloud builds submit backend --config backend/cloudbuild.yaml --substitutions=
          _REGION=us-central1,
          _REPO_NAME=storygen-repo,
          _SERVICE_NAME=genai-backend,
          COMMIT_SHA=$GITHUB_SHA
      env:
        PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and deploy frontend
      run: |
        gcloud builds submit frontend --config frontend/cloudbuild.yaml --substitutions=
          _REGION=us-central1,
          _REPO_NAME=storygen-repo,
          _SERVICE_NAME=genai-frontend,
          _BACKEND_URL=https://genai-backend-prod-123456-uc.a.run.app,
          COMMIT_SHA=$GITHUB_SHA
      env:
        PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
